server:
  port: 80

eureka:
  client:
    #表示是否要将自己注册进EurekaServer 默认为true
    registerWithEureka: false
    service-url:
      # defaultZone: http://localhost:7001/eureka  单机版
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #集群配置